# Generated by Django 4.1.5 on 2023-02-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_article_imagethumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
