# Generated by Django 4.1.5 on 2023-01-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_articles_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='_slug',
            new_name='slug',
        ),
    ]
