# Generated by Django 4.1.5 on 2023-02-01 23:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='imageThumbnail',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[280, 358], upload_to=''),
        ),
    ]
